name: WF DOCKER
run-name: DCOKER WF🚀
on: [push]
jobs:
  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Secret action
      with: # Set the secret as an input
        super_secret: ${{ secrets.SECRET }}
      env: # Or as an environment variable
        super_secret: ${{ secrets.SECRET }}
